<?php

namespace Bakgat\Notos\__CG__\Bakgat\Notos\Domain\Model\Resource;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Image extends \Bakgat\Notos\Domain\Model\Resource\Image implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Bakgat\\Notos\\Domain\\Model\\Resource\\Image' . "\0" . 'title', '' . "\0" . 'Bakgat\\Notos\\Domain\\Model\\Resource\\Image' . "\0" . 'description', '' . "\0" . 'Bakgat\\Notos\\Domain\\Model\\Resource\\Image' . "\0" . 'directory', '' . "\0" . 'Bakgat\\Notos\\Domain\\Model\\Resource\\Image' . "\0" . 'filename', '' . "\0" . 'Bakgat\\Notos\\Domain\\Model\\Resource\\Image' . "\0" . 'mime', '' . "\0" . 'Bakgat\\Notos\\Domain\\Model\\Resource\\Image' . "\0" . 'time_shot', '' . "\0" . 'Bakgat\\Notos\\Domain\\Model\\Resource\\Image' . "\0" . 'exif');
        }

        return array('__isInitialized__', '' . "\0" . 'Bakgat\\Notos\\Domain\\Model\\Resource\\Image' . "\0" . 'title', '' . "\0" . 'Bakgat\\Notos\\Domain\\Model\\Resource\\Image' . "\0" . 'description', '' . "\0" . 'Bakgat\\Notos\\Domain\\Model\\Resource\\Image' . "\0" . 'directory', '' . "\0" . 'Bakgat\\Notos\\Domain\\Model\\Resource\\Image' . "\0" . 'filename', '' . "\0" . 'Bakgat\\Notos\\Domain\\Model\\Resource\\Image' . "\0" . 'mime', '' . "\0" . 'Bakgat\\Notos\\Domain\\Model\\Resource\\Image' . "\0" . 'time_shot', '' . "\0" . 'Bakgat\\Notos\\Domain\\Model\\Resource\\Image' . "\0" . 'exif');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Image $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', array($title));

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function title()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'title', array());

        return parent::title();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function description()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'description', array());

        return parent::description();
    }

    /**
     * {@inheritDoc}
     */
    public function setDirectory($directory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDirectory', array($directory));

        return parent::setDirectory($directory);
    }

    /**
     * {@inheritDoc}
     */
    public function directory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'directory', array());

        return parent::directory();
    }

    /**
     * {@inheritDoc}
     */
    public function setFilename($filename)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFilename', array($filename));

        return parent::setFilename($filename);
    }

    /**
     * {@inheritDoc}
     */
    public function filename()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'filename', array());

        return parent::filename();
    }

    /**
     * {@inheritDoc}
     */
    public function setMime($mime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMime', array($mime));

        return parent::setMime($mime);
    }

    /**
     * {@inheritDoc}
     */
    public function mime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'mime', array());

        return parent::mime();
    }

    /**
     * {@inheritDoc}
     */
    public function setTimeShot(\DateTime $time_shot)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTimeShot', array($time_shot));

        return parent::setTimeShot($time_shot);
    }

    /**
     * {@inheritDoc}
     */
    public function timeShot()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'timeShot', array());

        return parent::timeShot();
    }

    /**
     * {@inheritDoc}
     */
    public function setExif($exif)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExif', array($exif));

        return parent::setExif($exif);
    }

    /**
     * {@inheritDoc}
     */
    public function exif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'exif', array());

        return parent::exif();
    }

    /**
     * {@inheritDoc}
     */
    public function id()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'id', array());

        return parent::id();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(\Bakgat\Notos\Domain\Model\Identity\Name $name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function name()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'name', array());

        return parent::name();
    }

    /**
     * {@inheritDoc}
     */
    public function setParent(\Bakgat\Notos\Domain\Model\Resource\Resource $parent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParent', array($parent));

        return parent::setParent($parent);
    }

    /**
     * {@inheritDoc}
     */
    public function parent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'parent', array());

        return parent::parent();
    }

    /**
     * {@inheritDoc}
     */
    public function prePersist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'prePersist', array());

        return parent::prePersist();
    }

    /**
     * {@inheritDoc}
     */
    public function preUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'preUpdate', array());

        return parent::preUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTime $createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($createdAt));

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', array());

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTime $updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', array($updatedAt));

        return parent::setUpdatedAt($updatedAt);
    }

}
